#!/bin/bash

read -p "请输入域名: " domain


# 检查系统是否安装了amass命令
echo  -e "\033[39m* * * * * * * * * * * * * * * * * * * * * * * * *\033[0m"
echo  -e "\033[39m* * * * * * * * * * Amass * * * * * * * * * *\033[0m"
echo  -e "\033[39m* * * * * * * * * * * * * * * * * * * * * * * * *\033[0m\n"
amass_path=$(command -v amass)
echo -e "\n\033[34mamass_path:\033[0m"
echo -e "\033[33m$amass_path\033[0m\n"


if [ -z "$amass_path" ]; then
  # 如果没有找到amass命令，打印错误信息并退出脚本
  echo -e "\e[1;31m系统中未找到amass命令\e[0m"
  exit 1
else
  # 如果找到amass命令，执行子域名搜索操作
  echo "开始搜索域名的子域名..."
  proxychains4 $amass_path enum -passive -d "$domain" >  $domain.txt
  
  echo -e "\033[35mAmass Done!!!\033[0m\n"
fi


#检查系统是否安装了 Httprobe 命令
echo  -e "\033[36m* * * * * * * * * * * * * * * * * * * * * * * * *\033[0m"
echo  -e "\033[36m* * * * * * * * * * Httprobe * * * * * * * * * *\033[0m"
echo  -e "\033[36m* * * * * * * * * * * * * * * * * * * * * * * * *\033[0m\n"
httprobe_path=$(command -v httprobe)
echo -e "\n\033[34mHttprobe_path:\033[0m"
echo -e "\033[33m$httprobe_path\033[0m\n"

if [ -z "$httprobe_path" ]; then
  # 如果没有找到httprobe命令，打印错误信息并退出脚本
  echo -e "\e[1;31m系统中未找到httprobe命令\e[0m"
  exit 1
else
  # 如果找到amass命令，执行子域名搜索操作
  echo "开始搜索子域名的80，443 端口..."
  proxychains4 cat $domain.txt | $httprobe_path >   $domain-httprobe.txt
  
  echo -e "\033[35mHttprobe Done!!!\033[0m\n"
fi


#检查系统是否安装了 Httpx 命令
echo  -e "\033[37m* * * * * * * * * * * * * * * * * * * * * * * * *\033[0m"
echo  -e "\033[37m* * * * * * * * * * Httpx * * * * * * * * * *\033[0m"
echo  -e "\033[37m* * * * * * * * * * * * * * * * * * * * * * * * *\033[0m\n"
httpx_path=$(command -v httpx)
echo -e "\n\033[38mHttpx_path:\033[0m"
echo -e "\033[38m$httpx_path\033[0m\n"

if [ -z "$httpx_path" ]; then
  # 如果没有找到httprobe命令，打印错误信息并退出脚本
  echo -e "\e[1;31m系统中未找到httprobe命令\e[0m"
  exit 1
else
  # 如果找到amass命令，执行子域名搜索操作
  echo "开始搜索域名的存活..."
  proxychains4 cat $domain-httprobe.txt | $httpx_path -status-code -location -title -server -td -method -websocket -ip -cname -cdn -silent -prode -asn    >   $domain-httpx.txt
  
  echo -e "\033[35mHttpx Done!!!\033[0m\n"
fi


